//author: Aritra Dhar
//Intern
//Accenture Technology Labs
//version 1.0


package selfExecutingCmdLine;

import java.io.*;
import java.util.*;

//this class will remove the <!DOCTYPE> from the XMLs which are generated by the soot
public class DoctypeRemover 
{
	public static String filepath;
	public void setFilePath(String path)
	{
		filepath=path;
	}
	public void DocTypeRemover() throws Exception
	{
		List<String> lst=new ArrayList<String>();
		lst.add(filepath);
		
		for(String s: lst)
		{
			String fs=s;
			String fs_tmp=s.substring(0, s.indexOf(".xml"));
			fs_tmp=fs_tmp.concat(".TMP");
			BufferedReader br=new BufferedReader(new InputStreamReader(new DataInputStream(new FileInputStream(fs))));
			FileWriter fwrite=new FileWriter(fs_tmp);
			String l=new String("");
			while((l=br.readLine())!=null)
			{
				if(!l.equals("<!DOCTYPE jil SYSTEM \"http://www.sable.mcgill.ca/~flynn/jil/jil10.dtd\">") || !l.contains("<!DOCTYPE"))
				{
					if(!l.contains("&amp;"))
						fwrite.append(l.replaceAll("&", "&amp;"));  //malfold xml handling by soot
					
					else if(l.contains("&amp;"))
						fwrite.append(l);
						
					fwrite.append("\n");
				}
			}
			br.close();
			fwrite.close();
			
			BufferedReader br1=new BufferedReader(new InputStreamReader(new DataInputStream(new FileInputStream(fs_tmp))));
			FileWriter fwrite1=new FileWriter(fs);
		
			String lw=new String("");	
			while((lw=br1.readLine())!=null)
			{
				fwrite1.append(lw);
				fwrite1.append("\n");
			}
		
			br1.close();
			fwrite1.close();
		
			File f=new File(fs_tmp);
			f.delete();
			System.out.println(" ---- doctype removal done ---- ");
		}
	}

}
